spring:
  datasource:
    url: jdbc:mysql://seb44main028-db.cx1erli3wray.ap-northeast-2.rds.amazonaws.com:13306
    username: ${{secret.RDS_MYSQL_ADMIN_ID}}
    password: ${{secret.RDS_MYSQL_ADMIN_PASSWORD}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true
aws:
  paramstore:
    enabled: true
    prefix: /spring-boot-aws
    name: seb44main028-ec2
    profileSeparator: _
