spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playpack?serverTimezone=UTC&characterEncoding=UTF-8
    username: //
    password: //
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URL}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG