spring:
  datasource:
    url: jdbc:mysql://${{secrets.RDS_ENDPOINT}}:${{secrets.RDS_PORT}}
    username: ${{secrets.RDS_Mysql_Admin_id}}
    password: ${{secrets.RDS_Mysql_Admin_password}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true
